# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
"""Named constants for AgentMesh configuration values."""

# Trust Score Thresholds (0-1000 scale)
TRUST_SCORE_MIN = 0
TRUST_SCORE_MAX = 1000
TRUST_SCORE_DEFAULT = 500
TRUST_REVOCATION_THRESHOLD = 300
TRUST_WARNING_THRESHOLD = 500

# Trust Tier Thresholds
TIER_VERIFIED_PARTNER_THRESHOLD = 900
TIER_TRUSTED_THRESHOLD = 700
TIER_STANDARD_THRESHOLD = 500
TIER_PROBATIONARY_THRESHOLD = 300

# Trust Dimension Weights (must sum to 1.0)
WEIGHT_POLICY_COMPLIANCE = 0.25
WEIGHT_RESOURCE_EFFICIENCY = 0.15
WEIGHT_OUTPUT_QUALITY = 0.20
WEIGHT_SECURITY_POSTURE = 0.25
WEIGHT_COLLABORATION_HEALTH = 0.15

# Risk Score Thresholds
RISK_CRITICAL_THRESHOLD = 200
RISK_HIGH_THRESHOLD = 400
RISK_ALERT_THRESHOLD = 600
RISK_MINIMAL_THRESHOLD = 800

# Risk Severity Weights
RISK_WEIGHT_CRITICAL = 1.0
RISK_WEIGHT_HIGH = 0.75
RISK_WEIGHT_MEDIUM = 0.5
RISK_WEIGHT_LOW = 0.25
RISK_WEIGHT_INFO = 0.1

# Credential Management
CREDENTIAL_ROTATION_THRESHOLD_SECONDS = 60

# Reward Engine
REWARD_UPDATE_INTERVAL_SECONDS = 30

# Risk Scoring
RISK_UPDATE_INTERVAL_SECONDS = 30

# Scope Chain
DEFAULT_DELEGATION_MAX_DEPTH = 5
