"""Policy generator CLI — generates YAML policy files from templates.

Reduces the OPA/Rego learning curve by providing ready-made policy
templates that work out of the box with AGT's PolicyEvaluator.

Usage:
    agent-os policy generate --template strict
    agent-os policy generate --template permissive -o my-policy.yaml
"""

from __future__ import annotations

import argparse
import sys
from typing import Any

import yaml

TEMPLATES: dict[str, dict[str, Any]] = {
    "strict": {
        "version": "1.0",
        "rules": [
            {"action": "web_search", "effect": "allow"},
            {"action": "read_file", "effect": "allow"},
            {
                "action": "*",
                "effect": "deny",
                "reason": "Strict mode: all actions blocked by default",
            },
        ],
        "content_filters": {
            "blocked_patterns": [
                r"\b\d{3}-\d{2}-\d{4}\b",   # SSN
                r"\b\d{16}\b",               # Credit card
            ],
        },
        "settings": {
            "require_human_approval": True,
            "max_tool_calls_per_session": 20,
            "log_level": "audit",
        },
    },
    "permissive": {
        "version": "1.0",
        "rules": [
            {
                "action": "*",
                "effect": "allow",
                "reason": "Permissive mode: all actions allowed (dev/test only)",
            },
        ],
        "content_filters": {
            "blocked_patterns": [
                r"\b\d{3}-\d{2}-\d{4}\b",   # SSN
                r"\b\d{16}\b",               # Credit card
            ],
        },
        "settings": {
            "require_human_approval": False,
            "max_tool_calls_per_session": 100,
            "log_level": "info",
        },
    },
    "web-only": {
        "version": "1.0",
        "rules": [
            {"action": "web_search", "effect": "allow"},
            {"action": "web_browse", "effect": "allow"},
            {
                "action": "*",
                "effect": "deny",
                "reason": "Web-only mode: only web actions allowed",
            },
        ],
        "content_filters": {
            "blocked_patterns": [
                r"\b\d{3}-\d{2}-\d{4}\b",
                r"\b\d{16}\b",
            ],
        },
        "settings": {
            "require_human_approval": False,
            "max_tool_calls_per_session": 50,
            "log_level": "info",
        },
    },
    "read-only": {
        "version": "1.0",
        "rules": [
            {"action": "read_file", "effect": "allow"},
            {"action": "list_directory", "effect": "allow"},
            {"action": "web_search", "effect": "allow"},
            {
                "action": "*",
                "effect": "deny",
                "reason": "Read-only mode: no write or execute actions",
            },
        ],
        "content_filters": {
            "blocked_patterns": [
                r"\b\d{3}-\d{2}-\d{4}\b",
                r"\b\d{16}\b",
            ],
        },
        "settings": {
            "require_human_approval": False,
            "max_tool_calls_per_session": 50,
            "log_level": "info",
        },
    },
    "custom": {
        "version": "1.0",
        "rules": [
            {"action": "REPLACE_ME", "effect": "allow"},
            {
                "action": "*",
                "effect": "deny",
                "reason": "Custom template: edit rules to match your needs",
            },
        ],
        "content_filters": {"blocked_patterns": []},
        "settings": {
            "require_human_approval": False,
            "max_tool_calls_per_session": 50,
            "log_level": "info",
        },
    },
}

TEMPLATE_CHOICES = list(TEMPLATES.keys())


def generate_policy(template_name: str) -> str:
    """Generate a YAML policy string from a named template."""
    if template_name not in TEMPLATES:
        raise ValueError(
            f"Unknown template '{template_name}'. "
            f"Choose from: {', '.join(TEMPLATE_CHOICES)}"
        )

    header = (
        f"# AGT Policy — {template_name} template\n"
        f"# Generated by: agent-os policy generate --template {template_name}\n"
    )
    body = yaml.dump(TEMPLATES[template_name], default_flow_style=False, sort_keys=False)
    return header + body


def cmd_policy_gen(argv: list[str] | None = None) -> None:
    """CLI entry point for policy generation."""
    parser = argparse.ArgumentParser(
        prog="agent-os policy generate",
        description="Generate YAML governance policies from templates.",
    )
    parser.add_argument(
        "--template",
        choices=TEMPLATE_CHOICES,
        default="strict",
        help="Policy template to use (default: strict)",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output file path. Defaults to stdout.",
    )
    args = parser.parse_args(argv)

    policy_yaml = generate_policy(args.template)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(policy_yaml)
        print(f"✅ Policy written to {args.output}", file=sys.stderr)
    else:
        print(policy_yaml)


if __name__ == "__main__":
    cmd_policy_gen()
