# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
"""
Example usage of Ghost Mode (Passive Observation).

This demonstrates:
1. Background daemon that observes silently
2. Dry-run analysis without taking action
3. Confidence-based surfacing
4. Learning user behavior patterns (Context Shadow)
5. The "No UI" paradigm - invisible until indispensable
"""

import time
import sys
import os

# Add parent directory to path to allow imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.ghost_mode import (
    GhostModeObserver,
    ContextShadow,
    BehaviorPattern,
    ObservationResult
)


def surfacing_callback(observation: ObservationResult):
    """
    Callback function that gets triggered when an observation should surface.
    
    In a real system, this might:
    - Show a notification
    - Log to monitoring system
    - Trigger an automated action
    - Send an alert
    """
    print("\n" + "="*60)
    print("🔔 SURFACING TO USER")
    print("="*60)
    print(f"Confidence: {observation.confidence:.2f} ({observation.get_confidence_level().value.upper()})")
    print(f"Observation: {observation.observation}")
    if observation.recommendation:
        print(f"💡 Recommendation: {observation.recommendation}")
    print("="*60 + "\n")


def demo_ghost_mode_basics():
    """
    Demo 1: Basic Ghost Mode operation.
    
    Shows how the observer runs in the background and processes signals
    without blocking or interfering with the main application.
    """
    print("="*60)
    print("DEMO 1: Ghost Mode Basics")
    print("="*60)
    print("\nThe observer daemon runs in the background...")
    print("It watches silently and only surfaces when confident.\n")
    
    # Create observer with callback
    observer = GhostModeObserver(
        confidence_threshold=0.7,
        surfacing_callback=surfacing_callback
    )
    
    # Start the daemon (runs in background thread)
    observer.start_observing(poll_interval=0.5)
    print("✓ Ghost Mode Observer started (running in background)")
    
    # Simulate signals being generated by the application
    print("\nSimulating application signals...")
    
    # Signal 1: Regular file change (low confidence, won't surface)
    observer.observe_signal({
        "type": "file_change",
        "data": {
            "file_path": "/src/utils.py",
            "change_type": "modified"
        },
        "user_id": "user123"
    })
    print("  • File change signal sent (low confidence)")
    time.sleep(0.6)
    
    # Signal 2: Security-sensitive file (high confidence, will surface)
    observer.observe_signal({
        "type": "file_change",
        "data": {
            "file_path": "/config/secrets.yaml",
            "change_type": "modified"
        },
        "user_id": "user123"
    })
    print("  • Security file change signal sent (high confidence)")
    time.sleep(0.6)
    
    # Signal 3: Error log (high confidence, will surface)
    observer.observe_signal({
        "type": "log_stream",
        "data": {
            "level": "ERROR",
            "message": "Database connection failed: timeout after 30s"
        },
        "user_id": "user123"
    })
    print("  • Error log signal sent (high confidence)")
    time.sleep(0.6)
    
    # Stop the daemon
    observer.stop_observing()
    print("\n✓ Ghost Mode Observer stopped")
    
    # Show statistics
    stats = observer.get_stats()
    print("\n" + "="*60)
    print("OBSERVATION STATISTICS")
    print("="*60)
    print(f"Signals Processed: {stats['signals_processed']}")
    print(f"Signals Surfaced: {stats['signals_surfaced']}")
    print(f"Surfacing Rate: {stats['surfacing_rate']:.1%}")
    print(f"Total Observations: {stats['total_observations']}")
    
    # Show recent observations
    print("\nRecent Observations:")
    for obs in observer.get_recent_observations(limit=5):
        print(f"  • [{obs.get_confidence_level().value}] {obs.observation}")


def demo_context_shadow():
    """
    Demo 2: Context Shadow - Learning User Behavior Patterns.
    
    The "Cookies of the real world" - secure local storage of user workflows
    that can be queried by other agents.
    """
    print("\n\n" + "="*60)
    print("DEMO 2: Context Shadow (Behavior Learning)")
    print("="*60)
    print("\nLearning user workflows to provide proactive assistance...")
    
    # Create context shadow for a specific user
    shadow = ContextShadow(user_id="user123")
    
    # Scenario: Learn expense filing workflow
    print("\n📊 Learning Pattern: Expense Filing Workflow")
    
    expense_pattern = BehaviorPattern(
        pattern_id="expense_filing_001",
        name="Weekly Expense Filing",
        description="User files expenses every Friday afternoon",
        trigger="open_expense_form",
        steps=[
            "Open expense report form",
            "Attach receipt image",
            "Fill in amount and category",
            "Add business justification",
            "Submit for approval"
        ],
        frequency=1,
        last_seen="2024-01-05T16:30:00",
        confidence=0.7
    )
    
    shadow.learn_pattern(expense_pattern)
    print(f"  ✓ Learned pattern: {expense_pattern.name}")
    print(f"    Trigger: {expense_pattern.trigger}")
    print(f"    Steps: {len(expense_pattern.steps)} steps")
    print(f"    Confidence: {expense_pattern.confidence:.2f}")
    
    # Simulate pattern reinforcement (user does it again)
    print("\n📈 User repeats the workflow...")
    expense_pattern_repeat = BehaviorPattern(
        pattern_id="expense_filing_001",  # Same ID
        name="Weekly Expense Filing",
        description="User files expenses every Friday afternoon",
        trigger="open_expense_form",
        steps=expense_pattern.steps,
        frequency=1,  # Will be incremented
        last_seen="2024-01-12T16:30:00",
        confidence=0.7  # Will be increased
    )
    
    shadow.learn_pattern(expense_pattern_repeat)
    
    # Query the learned pattern
    updated_pattern = shadow.get_pattern("expense_filing_001")
    print(f"  ✓ Pattern reinforced!")
    print(f"    Frequency: {updated_pattern.frequency} times")
    print(f"    Confidence: {updated_pattern.confidence:.2f}")
    
    # Query patterns by trigger
    print("\n🔍 Query: 'What does user do when opening expense form?'")
    matching_patterns = shadow.query_patterns(
        trigger="open_expense_form",
        min_confidence=0.5
    )
    
    if matching_patterns:
        pattern = matching_patterns[0]
        print(f"  Found pattern: {pattern.name}")
        print(f"  Expected next steps:")
        for i, step in enumerate(pattern.steps, 1):
            print(f"    {i}. {step}")
    
    # Show statistics
    print("\n" + "="*60)
    print("CONTEXT SHADOW STATISTICS")
    print("="*60)
    stats = shadow.get_stats()
    print(f"Total Patterns: {stats['total_patterns']}")
    print(f"High Confidence: {stats['high_confidence_patterns']}")
    print(f"Average Confidence: {stats['average_confidence']:.2f}")
    print(f"Most Frequent: {stats['most_frequent_pattern']}")


def demo_integrated_workflow():
    """
    Demo 3: Integrated workflow showing Ghost Mode + Context Shadow.
    
    This shows the full power of the system:
    - Observer watches in background
    - Learns user patterns
    - Surfaces proactive suggestions
    """
    print("\n\n" + "="*60)
    print("DEMO 3: Integrated Ghost Mode + Context Shadow")
    print("="*60)
    print("\nThe complete 'invisible until indispensable' experience...\n")
    
    # Create context shadow and observer
    shadow = ContextShadow(user_id="user456")
    observer = GhostModeObserver(
        context_shadow=shadow,
        confidence_threshold=0.6,  # Lower threshold for demo
        surfacing_callback=surfacing_callback
    )
    
    # Start observing
    observer.start_observing(poll_interval=0.3)
    print("✓ Ghost Mode active - watching silently\n")
    
    # Simulate user workflow: Code review process
    print("📝 User Workflow: Code Review Process")
    
    # Action 1: Open pull request
    observer.observe_signal({
        "type": "user_action",
        "data": {
            "action": "open_pull_request",
            "sequence": ["open_pull_request"]
        },
        "user_id": "user456"
    })
    print("  1. User opens pull request")
    time.sleep(0.4)
    
    # Action 2: Review changes
    observer.observe_signal({
        "type": "user_action",
        "data": {
            "action": "open_pull_request",
            "sequence": ["open_pull_request", "review_changes"]
        },
        "user_id": "user456"
    })
    print("  2. User reviews changes")
    time.sleep(0.4)
    
    # Action 3: Add comments
    observer.observe_signal({
        "type": "user_action",
        "data": {
            "action": "open_pull_request",
            "sequence": ["open_pull_request", "review_changes", "add_comments"]
        },
        "user_id": "user456"
    })
    print("  3. User adds comments")
    time.sleep(0.4)
    
    # Action 4: Run tests (completes the pattern)
    observer.observe_signal({
        "type": "user_action",
        "data": {
            "action": "open_pull_request",
            "sequence": ["open_pull_request", "review_changes", "add_comments", "run_tests"]
        },
        "user_id": "user456"
    })
    print("  4. User runs tests")
    time.sleep(0.4)
    
    print("\n✓ Pattern learned: Code Review Workflow\n")
    
    # Now simulate user starting the workflow again
    print("🔄 User starts code review workflow again...")
    observer.observe_signal({
        "type": "user_action",
        "data": {
            "action": "open_pull_request",
            "sequence": ["open_pull_request"]
        },
        "user_id": "user456"
    })
    print("  • Ghost Mode recognizes the pattern and surfaces suggestion!")
    time.sleep(0.5)
    
    # Stop observing
    observer.stop_observing()
    
    # Final statistics
    print("\n" + "="*60)
    print("FINAL STATISTICS")
    print("="*60)
    stats = observer.get_stats()
    print(f"Signals Processed: {stats['signals_processed']}")
    print(f"Signals Surfaced: {stats['signals_surfaced']}")
    print(f"\nContext Shadow:")
    print(f"  Learned Patterns: {stats['context_shadow']['total_patterns']}")
    print(f"  High Confidence: {stats['context_shadow']['high_confidence_patterns']}")


def demo_dry_run_mode():
    """
    Demo 4: Dry Run Mode - Analysis without action.
    
    Shows how Ghost Mode analyzes signals without interfering,
    only surfacing when it has high-confidence value to add.
    """
    print("\n\n" + "="*60)
    print("DEMO 4: Dry Run Mode (Analysis Without Action)")
    print("="*60)
    print("\nThe observer analyzes but never interferes...\n")
    
    observer = GhostModeObserver(confidence_threshold=0.8)
    observer.start_observing(poll_interval=0.3)
    
    print("Sending various signals to observe dry-run behavior:\n")
    
    # Mix of signals with different confidence levels
    signals = [
        {
            "name": "Regular file save",
            "signal": {
                "type": "file_change",
                "data": {"file_path": "/src/app.py", "change_type": "modified"}
            },
            "expected": "Low confidence - won't surface"
        },
        {
            "name": "Test file modification",
            "signal": {
                "type": "file_change",
                "data": {"file_path": "/tests/test_app.py", "change_type": "modified"}
            },
            "expected": "Medium confidence - might not surface"
        },
        {
            "name": "Critical error log",
            "signal": {
                "type": "log_stream",
                "data": {"level": "CRITICAL", "message": "System out of memory"}
            },
            "expected": "High confidence - will surface"
        }
    ]
    
    for item in signals:
        observer.observe_signal(item["signal"])
        print(f"  • {item['name']}")
        print(f"    Expected: {item['expected']}")
        time.sleep(0.4)
    
    time.sleep(1.0)  # Let processing complete
    observer.stop_observing()
    
    # Show dry-run results
    print("\n" + "="*60)
    print("DRY RUN RESULTS")
    print("="*60)
    for obs in observer.get_recent_observations():
        level = obs.get_confidence_level().value.upper()
        surfaced = "✓ SURFACED" if obs.should_surface else "✗ Silent"
        print(f"\n{surfaced} [{level}] {obs.confidence:.2f}")
        print(f"  {obs.observation}")
        if obs.recommendation:
            print(f"  💡 {obs.recommendation}")


def main():
    """Run all Ghost Mode demonstrations."""
    print("\n")
    print("╔" + "="*58 + "╗")
    print("║" + " "*58 + "║")
    print("║" + "  👻 GHOST MODE (PASSIVE OBSERVATION) DEMONSTRATION  ".center(58) + "║")
    print("║" + " "*58 + "║")
    print("║" + "  The Observer Daemon Pattern: Invisible Until Indispensable  ".center(58) + "║")
    print("║" + " "*58 + "║")
    print("╚" + "="*58 + "╝")
    
    # Run all demos
    demo_ghost_mode_basics()
    demo_context_shadow()
    demo_integrated_workflow()
    demo_dry_run_mode()
    
    # Summary
    print("\n\n" + "="*60)
    print("KEY INSIGHTS")
    print("="*60)
    print("""
1. 👻 Ghost Mode: The observer runs in the background, never blocking
2. 🎯 Confidence-Based: Only surfaces when highly confident
3. 🧠 Context Shadow: Learns user patterns securely and locally
4. 🔄 Dry Run: Analyzes without taking action
5. 💡 Proactive: Surfaces suggestions based on learned patterns

The Lesson:
The future interface isn't a "Destination" (a website).
It is a Daemon (a background process).
It is invisible until it is indispensable.

🚀 Startup Opportunity: The "Context Shadow"
A lightweight desktop/browser daemon that securely "shadows" an employee,
learning their specific workflows. It builds a local "Behavior Model" that
can be queried by other Agents. The "Cookies" of the real world—a secure
way to store user context.
    """)


if __name__ == "__main__":
    main()
